spring.application.name=OrdexStep
server.port=8082

# -------------------------
# PostgreSQL - Neon
# -------------------------
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# -------------------------
# JPA / Hibernate Optimizado
# -------------------------
# Cambia 'update' a 'none' o 'validate' en producción para evitar escaneos pesados
spring.jpa.hibernate.ddl-auto=update
# Desactiva el log de SQL en producción para ahorrar CPU y memoria
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Mejora el rendimiento de inserciones
spring.jpa.properties.hibernate.jdbc.batch_size=20
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=0
spring.datasource.hikari.idle-timeout=20000
spring.datasource.hikari.max-lifetime=300000
spring.datasource.hikari.pool-name=haxliouPostgresPool

# -------------------------
# Ajustes de Sistema
# -------------------------
spring.web.resources.static-locations=classpath:/static/
spring.jpa.properties.hibernate.jdbc.time_zone=America/Bogota

# Desactivar JMX si no lo usas (ahorra un poco de memoria RAM)
spring.jmx.enabled=false
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL_APP}
spring.mail.password=${PASSWORD_EMAIL}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
logging.level.org.springframework.mail=DEBUG